### ISSUE TITLE
Não loga.

### ISSUE THREAD

**Issue by Murataeduardo** [marcosandrade22/sistema-de-estoque-web#4]
Boa tarde.

Realizei o download e instalação do sistema, porem não realiza o login com os dados informado.

**Comment by marcosandrade22** [comment]
Você consegue me passar como esta a tabela usuários?

**Comment by Murataeduardo** [comment]
Opa, bom dia.

Segue os dados da tabela de usuários:

`id_funcionario	nome_funcionario	alias_funcionario	email_funcionario	funcao_funcionario	senha_funcionario	unidade_operacao	status	departamento
1	Funcionário Padrão	funcionario	teste@teste.com	1	2e6f9b0d5885b6010f9167787445617f553a735f	1	1	17`

**Comment by marcosandrade22** [comment]
A tabela esta correta, habilite o log de erros para ver o motivo de não logar, na index.php da raiz procure por production e altere para development.

**Comment by renato71amorim** [comment]
Testei aqui tb, e tambem sem sucesso.

**Comment by marcosandrade22** [comment]
> Testei aqui tb, e tambem sem sucesso.


 habilite o log de erros para ver o motivo de não logar, na index.php da raiz procure por production e altere para development.

**Comment by rafaelsabino** [comment]
É realmente, fiz de tudo aqui, mudando pra development, habilitando logs, seguindo configuração descrita a risca e nada. Não cria log de nada e infelizmente não loga de forma alguma. Parece ser um sistema muito bom, mas ficamos só na expectativa de fazer funcionar.

**Comment by marcosandrade22** [comment]
Resolvido, atualizado o core system do codeigniter para corrigir problemas de session no php >=7
